name: Greetings from Hans

on:
  push:
    tags:
      - '*'
    tags-ignore:
      - 'latest'

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Hans
        MIDDLE_NAME: the
        LAST_NAME: Wurst
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
